# action.yml
name: "Code Review with ChatGPT"
description: "Automating code review using ChatGPT with Github Actions integration on PRs for code explanations and suggestions."
inputs:
  openai_api_key: # id of input
    description: "OpenAI API Key"
    required: true
    default: ""
  github_token: # id of input
    description: "Github API Key"
    required: true
    default: ""
  github_pr_id: # id of input
    description: "Github PR ID"
    required: true
    default: ""
  openai_engine: # id of input
    description: "GPT-3 models can understand and generate natural language. We offer four main models with different levels of power suitable for different tasks. Davinci is the most capable model, and Ada is the fastest."
    required: false
    default: "text-davinci-002"
  openai_temperature: # id of input
    description: "What sampling temperature to use. Higher values means the model will take more risks. Try 0.9 for more creative applications, and 0 (argmax sampling) for ones with a well-defined answer."
    required: false
    default: "0.5"
  openai_max_tokens: # id of input
    description: "The maximum number of tokens to generate in the completion."
    required: false
    default: "2048"
  auto_pr_descriptions: # id of input
    description: "Enable or disable auto fill pull request descriptions. Options: true, false"
    required: false
    default: "true"
  auto_code_review: # id of input
    description: "Enable or disable auto code review for pull request. Options: true, false"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run code review
      shell: bash
      run: python main.py --openai_api_key "${{ inputs.openai_api_key }}" --github_token "${{ inputs.github_token }}" --github_pr_id "${{ inputs.github_pr_id }}" --openai_engine "${{ inputs.openai_engine }}" --openai_temperature "${{ inputs.openai_temperature }}" --openai_max_tokens "${{ inputs.openai_max_tokens }}" --auto_pr_descriptions "${{ inputs.auto_pr_descriptions }}" --auto_code_review "${{ inputs.auto_code_review }}"
