name: Code Review

description: Perform code review using OpenAI ChatGPT

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run code review
      run: python robot.py

inputs:
  github_token:
    description: "GitHub token"
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}

  openai_api_key:
    description: "OpenAI API key"
    required: true
